version: "3.7"

services:
  git_clone:
    image: alpine:3.16
    volumes:
      - FE3_conciliation_worker_data:/app
    working_dir: /app
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PAT=${GIT_PAT}
    entrypoint: >
      /bin/sh -c "
      apk update && \
      apk add --no-cache git && \
      if [ -d '/app/.git' ]; then \
        cd /app && git pull; \
      else \
        git clone https://$GIT_USERNAME:$GIT_PAT@github.com/gaberuh/FE3-conciliation-worker.git /app; \
      fi && \
      exit 0
      "
    networks:
      - winlead
    deploy:
      restart_policy:
        condition: none

  requirements:
    image: python:3.12-slim-bookworm
    volumes:
      - FE3_conciliation_worker_data:/app_data
    working_dir: /app_data
    command: >
      /bin/sh -c "
      echo 'Esperando o git_clone finalizar...' && \
      until [ -d /app_data/.git ]; do echo 'Aguardando repositório ser clonado...'; sleep 5; done && \
      apt-get update && apt-get install -y tzdata bash openjdk-17-jre-headless && \
      cd /app_data && \
      pip install --upgrade pip && \
      pip install --no-cache-dir -r requirements.txt --target=/app_data/libs && \
      export PYTHONPATH=$PYTHONPATH:/app_data/libs && \
      echo 'Instalação completa, JVM pronta.' && \
      exit 0
      "
    depends_on:
      - git_clone
    networks:
      - winlead
    deploy:
      restart_policy:
        condition: none

  spark_worker:
    image: python:3.12-slim-bookworm
    volumes:
      - FE3_conciliation_worker_data:/app_data
    working_dir: /app_data
    environment:
      - PYTHONPATH=/app_data:/app_data/libs
      # --- CONFIGURAÇÕES DE AMBIENTE DO WORKER (MinIO e RabbitMQ) ---
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_SECURE=${MINIO_SECURE}
      - SPARK_MASTER=${SPARK_MASTER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
    command: >
      /bin/sh -c "
      echo 'Esperando o worker_requirements finalizar...' && \
      until [ -d /app_data/libs ]; do echo 'Aguardando dependências...'; sleep 5; done && \
      apt-get update && apt-get install -y openjdk-17-jre-headless && \
      java -version && \
      echo 'Iniciando Spark Worker...' && \
      python -m app.main
      "
    depends_on:
      - requirements
      - git_clone
    networks:
      - winlead
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  FE3_conciliation_worker_data:
    external: true

networks:
  winlead:
    external: true